# Generated by Django 6.0 on 2026-01-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('VENDOR', 'Vendor'), ('CLIENT', 'Client'), ('LAWYER', 'Lawyer')], db_index=True, default='CLIENT', max_length=10),
        ),
    ]
