# Generated by Django 6.0.1 on 2026-01-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_case_casephoto_incidentreport_notification_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="case",
            name="users_case_case_nu_fa6c22_idx",
        ),
        migrations.RemoveIndex(
            model_name="case",
            name="users_case_vendor__8b885a_idx",
        ),
        migrations.RemoveIndex(
            model_name="case",
            name="users_case_status_545f7f_idx",
        ),
        migrations.RemoveIndex(
            model_name="case",
            name="users_case_due_dat_f8fd48_idx",
        ),
        migrations.RemoveIndex(
            model_name="casephoto",
            name="users_casep_case_id_0ec75f_idx",
        ),
        migrations.RemoveIndex(
            model_name="incidentreport",
            name="users_incid_case_id_5847e3_idx",
        ),
        migrations.RemoveIndex(
            model_name="incidentreport",
            name="users_incid_submitt_4bb449_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="users_notif_user_id_1be17e_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="users_notif_created_3ee999_idx",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Admin"),
                    ("ADMIN", "Admin"),
                    ("VENDOR", "Vendor"),
                    ("CLIENT", "Client"),
                    ("LAWYER", "Lawyer"),
                ],
                db_index=True,
                default="CLIENT",
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="case",
            name="vendor",
        ),
        migrations.RemoveField(
            model_name="incidentreport",
            name="case",
        ),
        migrations.RemoveField(
            model_name="incidentreport",
            name="submitted_by",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="case",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
        migrations.DeleteModel(
            name="CasePhoto",
        ),
        migrations.DeleteModel(
            name="IncidentReport",
        ),
        migrations.DeleteModel(
            name="Case",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
