# Generated by Django 6.0 on 2026-01-29 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_remove_case_users_case_case_nu_fa6c22_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("outlook_message_id", models.CharField(max_length=255, unique=True)),
                ("subject", models.CharField(max_length=500)),
                ("from_email", models.EmailField(max_length=254)),
                ("from_name", models.CharField(blank=True, max_length=255, null=True)),
                ("received_at", models.DateTimeField()),
                ("body_preview", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Processing"),
                            ("PROCESSING", "Processing"),
                            ("EXTRACTED", "Data Extracted"),
                            ("FAILED", "Extraction Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "extracted_data",
                    models.JSONField(
                        blank=True,
                        help_text="Extracted structured data from email",
                        null=True,
                    ),
                ),
                ("extraction_notes", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("has_attachments", models.BooleanField(default=False)),
                ("attachment_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Email Message",
                "verbose_name_plural": "Email Messages",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=500)),
                ("attachment_id", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("size_bytes", models.IntegerField()),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Local storage path",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("download_url", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("EXTRACTED", "Extracted"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "extracted_text",
                    models.TextField(
                        blank=True, help_text="Raw text extracted from file", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="users.emailmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Attachment",
                "verbose_name_plural": "Email Attachments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OutlookIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_address", models.EmailField(max_length=254, unique=True)),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("token_expiry", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("ERROR", "Error"),
                            ("EXPIRED", "Token Expired"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "refresh_frequency",
                    models.IntegerField(
                        choices=[
                            (5, "Every 5 minutes"),
                            (15, "Every 15 minutes"),
                            (30, "Every 30 minutes"),
                            (60, "Every hour"),
                        ],
                        default=15,
                        help_text="Minutes between email checks",
                    ),
                ),
                ("last_checked", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("error_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outlook_integrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Outlook Integration",
                "verbose_name_plural": "Outlook Integrations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="users.outlookintegration",
            ),
        ),
        migrations.CreateModel(
            name="ExtractedCaseData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("MANUAL", "Manual Entry"),
                            ("PDF", "PDF Upload"),
                        ],
                        default="EMAIL",
                        max_length=20,
                    ),
                ),
                (
                    "case_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "claim_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "claimant_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "claimant_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "claimant_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "insured_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "insured_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("incident_date", models.DateField(blank=True, null=True)),
                (
                    "incident_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("incident_description", models.TextField(blank=True, null=True)),
                (
                    "incident_address",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "incident_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "incident_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "incident_postal_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "claim_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "claim_amount_currency",
                    models.CharField(default="USD", max_length=3),
                ),
                (
                    "claim_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "documents_mentioned",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of document types found in email/PDF",
                    ),
                ),
                (
                    "extracted_from_attachments",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Which attachment each field was extracted from",
                    ),
                ),
                (
                    "extraction_confidence",
                    models.FloatField(
                        default=0.0,
                        help_text="Confidence score (0-1) of data extraction",
                    ),
                ),
                (
                    "needs_review",
                    models.BooleanField(
                        default=False, help_text="Flag if data needs manual review"
                    ),
                ),
                ("review_notes", models.TextField(blank=True, null=True)),
                (
                    "mapped_case_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID of the mapped Case model (when created)",
                        null=True,
                    ),
                ),
                ("case_created_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extracted_case_data",
                        to="users.emailmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extracted Case Data",
                "verbose_name_plural": "Extracted Case Data",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["case_number"], name="users_extra_case_nu_25738f_idx"
                    ),
                    models.Index(
                        fields=["claim_number"], name="users_extra_claim_n_0dfb3b_idx"
                    ),
                    models.Index(
                        fields=["needs_review"], name="users_extra_needs_r_56e241_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailProcessingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("DEBUG", "Debug"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="What action was performed", max_length=100
                    ),
                ),
                ("message", models.TextField()),
                (
                    "data",
                    models.JSONField(
                        blank=True, help_text="Additional structured data", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processing_logs",
                        to="users.emailmessage",
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_logs",
                        to="users.outlookintegration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Processing Log",
                "verbose_name_plural": "Email Processing Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["integration", "created_at"],
                        name="users_email_integra_1e87e9_idx",
                    ),
                    models.Index(fields=["level"], name="users_email_level_547db2_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["status", "received_at"], name="users_email_status_af16da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["integration", "status"], name="users_email_integra_ef7b5f_idx"
            ),
        ),
    ]
