# Generated by Django 6.0 on 2026-02-03 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_emailintake_gmailoauthtoken_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_code",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("client_name", models.CharField(max_length=500)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("date_of_commencement", models.DateField(blank=True, null=True)),
                (
                    "insured_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "notice_134_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "claimant_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "income_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "driver_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "dl_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "rc_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "permit_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "spot_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "court_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "notice_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "rti_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "hospital_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "insurance_client",
                "ordering": ["client_name"],
                "indexes": [
                    models.Index(
                        fields=["client_code"], name="insurance_c_client__a6adc1_idx"
                    ),
                    models.Index(
                        fields=["client_name"], name="insurance_c_client__e09894_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InsuranceCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.IntegerField(blank=True, null=True)),
                (
                    "claim_number",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("client_name", models.CharField(max_length=500)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MACT", "MACT"),
                            ("CIVIL", "Civil"),
                            ("CRIMINAL", "Criminal"),
                            ("OTHER", "Other"),
                        ],
                        default="MACT",
                        max_length=20,
                    ),
                ),
                (
                    "crn",
                    models.CharField(
                        blank=True, help_text="Case Reference Number", max_length=100
                    ),
                ),
                ("case_receipt_date", models.DateField()),
                ("receipt_month", models.CharField(blank=True, max_length=20)),
                ("completion_date", models.DateTimeField(blank=True, null=True)),
                ("completion_month", models.CharField(blank=True, max_length=20)),
                ("case_due_date", models.DateField(blank=True, null=True)),
                (
                    "tat_days",
                    models.IntegerField(
                        blank=True, help_text="Turn Around Time in days", null=True
                    ),
                ),
                (
                    "sla_status",
                    models.CharField(
                        blank=True,
                        help_text="Service Level Agreement status",
                        max_length=20,
                    ),
                ),
                (
                    "case_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Full Case", "Full Case"),
                            ("Connected Case", "Connected Case"),
                            ("Partial Investigation", "Partial Investigation"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "investigation_report_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Draft", "Draft"),
                            ("Completed", "Completed"),
                            ("Dispatch", "Dispatch"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "full_case_status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("WIP", "Work In Progress"),
                            ("Completed", "Completed"),
                            ("Dispatch", "Dispatch"),
                            ("Closed", "Closed"),
                        ],
                        default="Open",
                        max_length=20,
                    ),
                ),
                ("scope_of_work", models.TextField(blank=True)),
                ("case_notes", models.TextField(blank=True)),
                ("policy_number", models.CharField(blank=True, max_length=100)),
                ("claimant_name", models.CharField(blank=True, max_length=500)),
                ("claimant_address", models.TextField(blank=True)),
                ("claimant_district", models.CharField(blank=True, max_length=200)),
                ("claimant_status", models.CharField(blank=True, max_length=50)),
                ("income_details", models.TextField(blank=True)),
                ("income_address", models.TextField(blank=True)),
                ("income_district", models.CharField(blank=True, max_length=200)),
                ("income_status", models.CharField(blank=True, max_length=50)),
                ("insured_name", models.CharField(blank=True, max_length=500)),
                ("insured_address", models.TextField(blank=True)),
                ("insured_district", models.CharField(blank=True, max_length=200)),
                ("notice_132", models.CharField(blank=True, max_length=50)),
                ("insured_status", models.CharField(blank=True, max_length=50)),
                ("driver_name", models.CharField(blank=True, max_length=500)),
                ("driver_address", models.TextField(blank=True)),
                ("driver_district", models.CharField(blank=True, max_length=200)),
                ("driver_status", models.CharField(blank=True, max_length=50)),
                ("dl_status", models.CharField(blank=True, max_length=50)),
                ("rc_status", models.CharField(blank=True, max_length=50)),
                ("permit_status", models.CharField(blank=True, max_length=50)),
                ("fitness_status", models.CharField(blank=True, max_length=50)),
                ("spot_location", models.TextField(blank=True)),
                ("spot_district", models.CharField(blank=True, max_length=200)),
                ("spot_status", models.CharField(blank=True, max_length=50)),
                ("fir_number", models.CharField(blank=True, max_length=100)),
                ("police_station", models.CharField(blank=True, max_length=200)),
                ("police_district", models.CharField(blank=True, max_length=200)),
                ("rti_status", models.CharField(blank=True, max_length=50)),
                ("chargesheet_status", models.CharField(blank=True, max_length=50)),
                ("hospital_name", models.CharField(blank=True, max_length=500)),
                ("hospital_address", models.TextField(blank=True)),
                ("hospital_district", models.CharField(blank=True, max_length=200)),
                ("hospital_status", models.CharField(blank=True, max_length=50)),
                ("dispatch_date", models.DateField(blank=True, null=True)),
                ("dispatch_status", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cases",
                        to="users.client",
                    ),
                ),
                (
                    "source_email",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_cases",
                        to="users.emailintake",
                    ),
                ),
            ],
            options={
                "db_table": "insurance_case",
                "ordering": ["-case_receipt_date"],
            },
        ),
        migrations.CreateModel(
            name="CaseDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("POLICY", "Policy Document"),
                            ("PETITION", "Petition Copy"),
                            ("FIR", "FIR Copy"),
                            ("MEDICAL", "Medical Report"),
                            ("SPOT_PHOTO", "Spot Photograph"),
                            ("DL", "Driving License"),
                            ("RC", "Registration Certificate"),
                            ("PERMIT", "Permit"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("document_name", models.CharField(max_length=500)),
                ("file_path", models.FileField(upload_to="case_documents/%Y/%m/%d/")),
                ("extracted_text", models.TextField(blank=True)),
                ("extracted_data", models.JSONField(blank=True, default=dict)),
                ("uploaded_date", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email_attachment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_case_documents",
                        to="users.emailattachment",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="users.insurancecase",
                    ),
                ),
            ],
            options={
                "db_table": "case_document",
                "ordering": ["-uploaded_date"],
            },
        ),
        migrations.AddIndex(
            model_name="insurancecase",
            index=models.Index(
                fields=["claim_number"], name="insurance_c_claim_n_381889_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insurancecase",
            index=models.Index(
                fields=["case_receipt_date"], name="insurance_c_case_re_da5463_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insurancecase",
            index=models.Index(
                fields=["full_case_status"], name="insurance_c_full_ca_b9d898_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insurancecase",
            index=models.Index(
                fields=["category"], name="insurance_c_categor_a449ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casedocument",
            index=models.Index(
                fields=["case", "document_type"], name="case_docume_case_id_654b60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casedocument",
            index=models.Index(
                fields=["uploaded_date"], name="case_docume_uploade_fbeb66_idx"
            ),
        ),
    ]
