# Generated by Django 6.0 on 2026-02-09 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_client_insurancecase_casedocument_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidencePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_id",
                    models.IntegerField(
                        db_index=True, help_text="Reference to cases_case table"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        help_text="Evidence photo with GPS metadata",
                        upload_to="evidence_photos/%Y/%m/%d/",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="GPS latitude from photo EXIF data (REQUIRED)",
                        max_digits=9,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="GPS longitude from photo EXIF data (REQUIRED)",
                        max_digits=9,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=500)),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_size",
                    models.BigIntegerField(default=0, help_text="File size in bytes"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_photos",
                        to="users.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "evidence_photo",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["case_id", "uploaded_at"],
                        name="evidence_ph_case_id_c8909b_idx",
                    ),
                    models.Index(
                        fields=["vendor", "uploaded_at"],
                        name="evidence_ph_vendor__b65e78_idx",
                    ),
                    models.Index(
                        fields=["case_id", "vendor"],
                        name="evidence_ph_case_id_ffa564_idx",
                    ),
                ],
            },
        ),
    ]
