# Generated by Django 6.0.1 on 2026-02-19 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_add_case_verification_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseverification",
            name="accident_brief",
            field=models.TextField(
                blank=True, help_text="Brief description of the accident"
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="bsn_sections",
            field=models.CharField(
                blank=True, help_text="BSN Sections applicable", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="check_status",
            field=models.CharField(
                blank=True, help_text="Check status (WIP/Completed/etc)", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="claimant_address",
            field=models.TextField(blank=True, help_text="Claimant address"),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="claimant_contact",
            field=models.CharField(
                blank=True, help_text="Claimant contact number", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="claimant_name",
            field=models.CharField(
                blank=True, help_text="Claimant name", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="court_name",
            field=models.CharField(blank=True, help_text="Court name", max_length=500),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="district",
            field=models.CharField(
                blank=True, help_text="District where accident occurred", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="dl_number",
            field=models.CharField(
                blank=True, help_text="Driving License number", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="driver_address",
            field=models.TextField(blank=True, help_text="Driver address"),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="driver_and_insured_same",
            field=models.BooleanField(
                default=False,
                help_text="Whether driver and insured are the same person",
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="driver_contact",
            field=models.CharField(
                blank=True, help_text="Driver contact number", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="driver_name",
            field=models.CharField(blank=True, help_text="Driver name", max_length=500),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="fir_delay_in_days",
            field=models.IntegerField(
                blank=True, help_text="Number of days delay in FIR filing", null=True
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="fir_number_claimant",
            field=models.CharField(
                blank=True, help_text="FIR Number for claimant check", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="fir_number_spot",
            field=models.CharField(
                blank=True, help_text="FIR Number for spot check", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="income",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Claimant income",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="insured_address",
            field=models.TextField(blank=True, help_text="Insured address"),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="insured_contact",
            field=models.CharField(
                blank=True, help_text="Insured contact number", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="insured_name",
            field=models.CharField(
                blank=True, help_text="Insured person name", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="ipc_sections",
            field=models.CharField(
                blank=True, help_text="IPC sections applicable", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="mv_act",
            field=models.CharField(
                blank=True, help_text="Motor Vehicle Act details", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="observations",
            field=models.TextField(
                blank=True, help_text="Observations during verification"
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="occupation",
            field=models.CharField(
                blank=True, help_text="Driver occupation", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="permit_driver",
            field=models.CharField(
                blank=True, help_text="Permit details for driver", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="permit_insured",
            field=models.CharField(
                blank=True, help_text="Permit details for insured", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="place_of_accident",
            field=models.CharField(
                blank=True, help_text="Place/location of accident", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="police_station",
            field=models.CharField(
                blank=True, help_text="Police station name", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="policy_number",
            field=models.CharField(
                blank=True, help_text="Insurance policy number", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="policy_period",
            field=models.CharField(
                blank=True, help_text="Policy period/validity", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="rc_number",
            field=models.CharField(
                blank=True, help_text="Registration Certificate number", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="statement",
            field=models.TextField(
                blank=True, help_text="Statement text for the verification"
            ),
        ),
        migrations.AddField(
            model_name="caseverification",
            name="time_of_accident",
            field=models.CharField(
                blank=True, help_text="Time when accident occurred", max_length=100
            ),
        ),
        migrations.CreateModel(
            name="ClaimantDependent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dependent_name",
                    models.CharField(help_text="Name of the dependent", max_length=500),
                ),
                (
                    "dependent_contact",
                    models.CharField(
                        blank=True,
                        help_text="Contact number of dependent",
                        max_length=20,
                    ),
                ),
                (
                    "dependent_address",
                    models.TextField(blank=True, help_text="Address of dependent"),
                ),
                (
                    "relationship",
                    models.CharField(
                        blank=True,
                        help_text="Relationship to claimant (spouse/child/parent/etc)",
                        max_length=100,
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        blank=True, help_text="Age of dependent", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this dependent was added"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        help_text="The case this dependent belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claimant_dependents",
                        to="users.insurancecase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Claimant Dependent",
                "verbose_name_plural": "Claimant Dependents",
                "db_table": "claimant_dependent",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["case"], name="claimant_de_case_id_94b8e5_idx")
                ],
            },
        ),
    ]
