# Generated by Django 6.0 on 2026-02-25 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_add_common_case_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="caseverification",
            name="description",
        ),
        migrations.RemoveField(
            model_name="caseverification",
            name="document_number",
        ),
        migrations.RemoveField(
            model_name="caseverification",
            name="document_type",
        ),
        migrations.RemoveField(
            model_name="caseverification",
            name="document_verified",
        ),
        migrations.RemoveField(
            model_name="caseverification",
            name="identification_number",
        ),
        migrations.RemoveField(
            model_name="caseverification",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="caseverification",
            name="location_address",
        ),
        migrations.RemoveField(
            model_name="caseverification",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="caseverification",
            name="person_address",
        ),
        migrations.RemoveField(
            model_name="caseverification",
            name="person_email",
        ),
        migrations.RemoveField(
            model_name="caseverification",
            name="person_name",
        ),
        migrations.RemoveField(
            model_name="caseverification",
            name="person_phone",
        ),
        migrations.RemoveField(
            model_name="caseverification",
            name="title",
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="accident_brief",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_verifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="bsn_sections",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verifications",
                to="users.insurancecase",
            ),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="check_status",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="claimant_address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="claimant_contact",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="claimant_name",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="court_name",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="district",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="dl_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="driver_address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="driver_and_insured_same",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="driver_contact",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="driver_name",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="findings",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="fir_delay_in_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="fir_number_claimant",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="fir_number_spot",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="income",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="insured_address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="insured_contact",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="insured_name",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="ipc_sections",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="mv_act",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="observations",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="occupation",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="permit_driver",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="permit_insured",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="place_of_accident",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="police_station",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="policy_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="policy_period",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="priority",
            field=models.CharField(
                choices=[
                    ("LOW", "Low"),
                    ("MEDIUM", "Medium"),
                    ("HIGH", "High"),
                    ("URGENT", "Urgent"),
                ],
                default="MEDIUM",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="rc_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="statement",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("VERIFIED", "Verified"),
                    ("REJECTED", "Rejected"),
                    ("REQUIRES_REVISION", "Requires Revision"),
                ],
                db_index=True,
                default="PENDING",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="time_of_accident",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="verification_type",
            field=models.CharField(
                choices=[
                    ("CLAIMANT_CHECK", "Claimant Verification"),
                    ("INSURED_CHECK", "Insured Verification"),
                    ("DRIVER_CHECK", "Driver Verification"),
                    ("SPOT_CHECK", "Spot Investigation"),
                    ("CHARGESHEET", "Chargesheet Verification"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="caseverification",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_verifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="claimantdependent",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="claimantdependent",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claimant_dependents",
                to="users.insurancecase",
            ),
        ),
        migrations.AlterField(
            model_name="claimantdependent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="claimantdependent",
            name="dependent_address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="claimantdependent",
            name="dependent_contact",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="claimantdependent",
            name="dependent_name",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="claimantdependent",
            name="relationship",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="claimantdependent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="verificationcomment",
            name="comment",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="verificationcomment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="verificationcomment",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verification_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="verificationcomment",
            name="is_internal",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="verificationcomment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="verificationcomment",
            name="verification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="users.caseverification",
            ),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("PHOTO", "Photograph"),
                    ("SCAN", "Scanned Document"),
                    ("PDF", "PDF Document"),
                    ("VIDEO", "Video Recording"),
                    ("AUDIO", "Audio Recording"),
                    ("REPORT", "Investigation Report"),
                    ("STATEMENT", "Written Statement"),
                    ("CERTIFICATE", "Certificate"),
                    ("OTHER", "Other"),
                ],
                default="PHOTO",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="file_name",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="file_path",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="file_size",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="mime_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_verification_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="verification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="users.caseverification",
            ),
        ),
    ]
