# Generated by Django 6.0.1 on 2026-03-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_create_rti_rto_check_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseverification',
            name='verification_type',
            field=models.CharField(choices=[('CLAIMANT_CHECK', 'Claimant Verification'), ('INSURED_CHECK', 'Insured Verification'), ('DRIVER_CHECK', 'Driver Verification'), ('SPOT_CHECK', 'Spot Investigation'), ('CHARGESHEET', 'Chargesheet Verification'), ('RTI_CHECK', 'RTI Verification'), ('RTO_CHECK', 'RTO Verification')], db_index=True, max_length=50),
        ),
    ]
