# Generated by Django 6.0.1 on 2026-03-25 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_create_statement_audio_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancecase',
            name='receive_month',
            field=models.CharField(blank=True, help_text='Month of receive', max_length=20),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_content', models.TextField(help_text='AI-generated report content')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Lawyer review notes or rejection reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_lawyer', models.ForeignKey(blank=True, limit_choices_to={'role': 'LAWYER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.insurancecase')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case', 'status'], name='reports_case_id_a8cae1_idx'), models.Index(fields=['assigned_lawyer', 'status'], name='reports_assigne_9bcb07_idx'), models.Index(fields=['status'], name='reports_status_e83c1d_idx'), models.Index(fields=['created_at'], name='reports_created_c5f642_idx')],
            },
        ),
    ]
