# Generated by Django 6.0.1 on 2026-07-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20260720_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
