# Generated by Django 6.0.1 on 2026-07-28 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_alter_customuser_role_alter_customuser_sub_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('CASE_MANAGER', 'Case Manager'), ('VENDOR', 'Vendor'), ('CLIENT', 'Client'), ('QC', 'QC'), ('ADVOCATE', 'Advocate')], db_index=True, default='CLIENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='user',
            field=models.OneToOneField(limit_choices_to=models.Q(('role', 'VENDOR'), ('role', 'ADVOCATE'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
