# Generated by Django 6.0.1 on 2026-08-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_lawyer_options_and_more'),
        ('users', '0046_add_questionnaire_vendor_feedback_columns'),
        ('users', '0059_casedeletionrequest'),
        ('users', '0061_add_device_limit'),
    ]

    operations = [
    ]
