# Generated by Django 6.0.1 on 2026-08-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_delete_tatchangerequest'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE rto_checks DROP CONSTRAINT IF EXISTS rto_checks_check_status_check;
            ALTER TABLE rto_checks ADD CONSTRAINT rto_checks_check_status_check 
            CHECK (check_status IN ('Not Initiated', 'WIP', 'Completed', 'Stop', 'Verified', 'Reassigned', 'Unable to Verify', 'Failed Complete', 'Failed Complete '));
            UPDATE rto_checks SET check_status = 'Unable to Verify' WHERE check_status = 'Failed';
            """,
            reverse_sql="""
            ALTER TABLE rto_checks DROP CONSTRAINT IF EXISTS rto_checks_check_status_check;
            ALTER TABLE rto_checks ADD CONSTRAINT rto_checks_check_status_check 
            CHECK (check_status IN ('Not Initiated', 'WIP', 'Completed', 'Stop', 'Verified', 'Reassigned', 'Failed', 'Failed Complete', 'Failed Complete '));
            UPDATE rto_checks SET check_status = 'Failed' WHERE check_status = 'Unable to Verify';
            """
        )
    ]
