# Generated by Django 6.0.1 on 2026-08-26 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_update_rto_check_failed_status'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE chargesheets ADD COLUMN IF NOT EXISTS cs_received_photos JSONB DEFAULT '[]';
            """,
            reverse_sql="""
            ALTER TABLE chargesheets DROP COLUMN IF NOT EXISTS cs_received_photos;
            """
        )
    ]
