# Generated by Django 6.0 on 2026-01-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_emailverificationcode_passwordresettoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="sub_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CASE_HANDLER", "Case Handler"),
                    ("REPORT_MANAGER", "Report Manager"),
                    ("LOG_MANAGER", "Log Manager"),
                    ("SUPER_ADMIN", "Super Admin"),
                ],
                help_text="Sub-role for admin users only",
                max_length=20,
                null=True,
            ),
        ),
    ]
