# Generated by Django 6.0 on 2026-01-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customuser_sub_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="permissions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Custom page permissions for this user",
            ),
        ),
    ]
