# Generated by Django 6.0 on 2026-01-30 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_emailmessage_emailattachment_outlookintegration_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="outlookintegration",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Email Integration",
                "verbose_name_plural": "Email Integrations",
            },
        ),
        migrations.RemoveIndex(
            model_name="emailmessage",
            name="users_email_status_af16da_idx",
        ),
        migrations.RemoveIndex(
            model_name="emailmessage",
            name="users_email_integra_ef7b5f_idx",
        ),
        migrations.RemoveIndex(
            model_name="extractedcasedata",
            name="users_extra_case_nu_25738f_idx",
        ),
        migrations.RemoveField(
            model_name="emailattachment",
            name="extracted_text",
        ),
        migrations.RemoveField(
            model_name="emailattachment",
            name="processed_at",
        ),
        migrations.RemoveField(
            model_name="emailprocessinglog",
            name="data",
        ),
        migrations.AddField(
            model_name="emailattachment",
            name="extraction_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emailattachment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("EXTRACTED", "Extracted"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="emailprocessinglog",
            name="action",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="emailprocessinglog",
            name="email",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="users.emailmessage",
            ),
        ),
        migrations.AlterField(
            model_name="emailprocessinglog",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="users.outlookintegration",
            ),
        ),
        migrations.AlterField(
            model_name="emailprocessinglog",
            name="level",
            field=models.CharField(
                choices=[
                    ("DEBUG", "Debug"),
                    ("INFO", "Info"),
                    ("WARNING", "Warning"),
                    ("ERROR", "Error"),
                ],
                default="INFO",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="extractedcasedata",
            name="case_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="extractedcasedata",
            name="documents_mentioned",
            field=models.JSONField(
                blank=True, default=list, help_text="List of document types mentioned"
            ),
        ),
        migrations.AlterField(
            model_name="extractedcasedata",
            name="email",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extracted_case_data",
                to="users.emailmessage",
            ),
        ),
        migrations.AlterField(
            model_name="extractedcasedata",
            name="extraction_confidence",
            field=models.FloatField(default=0.5, help_text="Confidence score (0-1)"),
        ),
        migrations.AlterField(
            model_name="extractedcasedata",
            name="mapped_case_id",
            field=models.IntegerField(
                blank=True, help_text="ID of created case record", null=True
            ),
        ),
        migrations.AlterField(
            model_name="extractedcasedata",
            name="needs_review",
            field=models.BooleanField(
                default=False, help_text="Flag for manual review if confidence low"
            ),
        ),
        migrations.AlterField(
            model_name="extractedcasedata",
            name="source",
            field=models.CharField(
                default="EMAIL",
                help_text="Data source (EMAIL, MANUAL, API)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="outlookintegration",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="outlookintegration",
            name="refresh_frequency",
            field=models.IntegerField(
                default=15, help_text="Sync interval in minutes (5, 15, 30, 60)"
            ),
        ),
        migrations.AlterField(
            model_name="outlookintegration",
            name="refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="outlookintegration",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("ERROR", "Error"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="outlookintegration",
            name="token_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="emailattachment",
            index=models.Index(
                fields=["attachment_id"], name="users_email_attachm_0503b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailattachment",
            index=models.Index(fields=["status"], name="users_email_status_8b45a8_idx"),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["outlook_message_id"], name="users_email_outlook_56617c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["status", "created_at"], name="users_email_status_9941ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["from_email"], name="users_email_from_em_9cc08f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extractedcasedata",
            index=models.Index(
                fields=["mapped_case_id"], name="users_extra_mapped__3a13d3_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="extractedcasedata",
            name="claim_amount_currency",
        ),
        migrations.RemoveField(
            model_name="extractedcasedata",
            name="claim_status",
        ),
        migrations.RemoveField(
            model_name="extractedcasedata",
            name="extracted_from_attachments",
        ),
        migrations.RemoveField(
            model_name="extractedcasedata",
            name="incident_city",
        ),
        migrations.RemoveField(
            model_name="extractedcasedata",
            name="incident_postal_code",
        ),
        migrations.RemoveField(
            model_name="extractedcasedata",
            name="incident_state",
        ),
        migrations.RemoveField(
            model_name="extractedcasedata",
            name="incident_type",
        ),
        migrations.RemoveField(
            model_name="extractedcasedata",
            name="insured_email",
        ),
        migrations.RemoveField(
            model_name="extractedcasedata",
            name="review_notes",
        ),
    ]
