# Generated by Django 6.0 on 2026-02-03 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_outlookintegration_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailIntake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("thread_id", models.CharField(blank=True, max_length=255)),
                ("subject", models.CharField(max_length=500)),
                ("sender_email", models.EmailField(max_length=254)),
                ("sender_name", models.CharField(blank=True, max_length=255)),
                ("recipient_email", models.EmailField(max_length=254)),
                (
                    "cc_emails",
                    models.TextField(blank=True, help_text="Comma-separated CC emails"),
                ),
                (
                    "bcc_emails",
                    models.TextField(
                        blank=True, help_text="Comma-separated BCC emails"
                    ),
                ),
                ("body_text", models.TextField(blank=True)),
                ("body_html", models.TextField(blank=True)),
                ("received_at", models.DateTimeField()),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("processing_error", models.TextField(blank=True)),
                ("has_attachments", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="GmailOAuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                (
                    "token_uri",
                    models.URLField(default="https://oauth2.googleapis.com/token"),
                ),
                ("client_id", models.CharField(max_length=500)),
                ("client_secret", models.CharField(max_length=500)),
                ("scopes", models.TextField(help_text="JSON array of scopes")),
                ("expires_at", models.DateTimeField()),
                ("email_address", models.EmailField(max_length=254, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="emailmessage",
            name="users_email_outlook_56617c_idx",
        ),
        migrations.RemoveIndex(
            model_name="emailmessage",
            name="users_email_status_9941ab_idx",
        ),
        migrations.RemoveIndex(
            model_name="emailmessage",
            name="users_email_from_em_9cc08f_idx",
        ),
        migrations.RemoveIndex(
            model_name="emailprocessinglog",
            name="users_email_integra_1e87e9_idx",
        ),
        migrations.RemoveIndex(
            model_name="emailprocessinglog",
            name="users_email_level_547db2_idx",
        ),
        migrations.RemoveIndex(
            model_name="extractedcasedata",
            name="users_extra_claim_n_0dfb3b_idx",
        ),
        migrations.RemoveIndex(
            model_name="extractedcasedata",
            name="users_extra_needs_r_56e241_idx",
        ),
        migrations.RemoveIndex(
            model_name="extractedcasedata",
            name="users_extra_mapped__3a13d3_idx",
        ),
        migrations.RemoveField(
            model_name="outlookintegration",
            name="created_by",
        ),
        migrations.AlterModelOptions(
            name="emailattachment",
            options={"ordering": ["filename"]},
        ),
        migrations.RemoveIndex(
            model_name="emailattachment",
            name="users_email_attachm_0503b5_idx",
        ),
        migrations.RemoveIndex(
            model_name="emailattachment",
            name="users_email_status_8b45a8_idx",
        ),
        migrations.AddField(
            model_name="emailattachment",
            name="extracted_text",
            field=models.TextField(blank=True, help_text="Text extracted from PDF"),
        ),
        migrations.AddField(
            model_name="emailattachment",
            name="file_size",
            field=models.BigIntegerField(default=0, help_text="File size in bytes"),
        ),
        migrations.AddField(
            model_name="emailattachment",
            name="is_pdf",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="emailattachment",
            name="file_path",
            field=models.FileField(upload_to="email_attachments/%Y/%m/%d/"),
        ),
        migrations.AddIndex(
            model_name="emailintake",
            index=models.Index(
                fields=["message_id"], name="users_email_message_2cf35b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailintake",
            index=models.Index(
                fields=["processing_status", "created_at"],
                name="users_email_process_0136e6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailintake",
            index=models.Index(
                fields=["received_at"], name="users_email_receive_58bda6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailintake",
            index=models.Index(
                fields=["sender_email"], name="users_email_sender__01d30c_idx"
            ),
        ),
        migrations.AlterField(
            model_name="emailattachment",
            name="email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="users.emailintake",
            ),
        ),
        migrations.AddIndex(
            model_name="emailattachment",
            index=models.Index(
                fields=["email", "filename"], name="users_email_email_i_b4ffc6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailattachment",
            index=models.Index(
                fields=["content_type"], name="users_email_content_24018e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailattachment",
            index=models.Index(fields=["is_pdf"], name="users_email_is_pdf_f6b0e7_idx"),
        ),
        migrations.AddIndex(
            model_name="gmailoauthtoken",
            index=models.Index(
                fields=["email_address"], name="users_gmail_email_a_a3c333_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gmailoauthtoken",
            index=models.Index(
                fields=["is_active"], name="users_gmail_is_acti_e45f7a_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="emailmessage",
            name="integration",
        ),
        migrations.RemoveField(
            model_name="extractedcasedata",
            name="email",
        ),
        migrations.RemoveField(
            model_name="emailattachment",
            name="attachment_id",
        ),
        migrations.RemoveField(
            model_name="emailattachment",
            name="download_url",
        ),
        migrations.RemoveField(
            model_name="emailattachment",
            name="extraction_error",
        ),
        migrations.RemoveField(
            model_name="emailattachment",
            name="size_bytes",
        ),
        migrations.RemoveField(
            model_name="emailattachment",
            name="status",
        ),
        migrations.RemoveField(
            model_name="emailattachment",
            name="updated_at",
        ),
        migrations.DeleteModel(
            name="EmailProcessingLog",
        ),
        migrations.DeleteModel(
            name="OutlookIntegration",
        ),
        migrations.DeleteModel(
            name="EmailMessage",
        ),
        migrations.DeleteModel(
            name="ExtractedCaseData",
        ),
    ]
