# Generated by Django 6.0.1 on 2026-02-17 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_emailintake_gmailoauthtoken_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_code",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("client_name", models.CharField(max_length=500)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("date_of_commencement", models.DateField(blank=True, null=True)),
                (
                    "insured_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "notice_134_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "claimant_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "income_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "driver_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "dl_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "rc_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "permit_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "spot_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "court_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "notice_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "rti_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "hospital_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "insurance_client",
                "ordering": ["client_name"],
                "indexes": [
                    models.Index(
                        fields=["client_code"], name="insurance_c_client__a6adc1_idx"
                    ),
                    models.Index(
                        fields=["client_name"], name="insurance_c_client__e09894_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InsuranceCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_number",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MACT", "Motor Accident Claims Tribunal"),
                            ("CIVIL", "Civil Case"),
                            ("CRIMINAL", "Criminal Case"),
                            ("CONSUMER", "Consumer Forum"),
                            ("OTHER", "Other"),
                        ],
                        default="MACT",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("PENDING", "Pending"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "claim_number",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("client_code", models.CharField(blank=True, max_length=100)),
                ("insured_name", models.CharField(blank=True, max_length=500)),
                ("claimant_name", models.CharField(blank=True, max_length=500)),
                ("incident_address", models.TextField(blank=True)),
                ("incident_city", models.CharField(blank=True, max_length=200)),
                ("incident_state", models.CharField(blank=True, max_length=200)),
                ("incident_postal_code", models.CharField(blank=True, max_length=20)),
                ("incident_country", models.CharField(default="India", max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("formatted_address", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("MANUAL", "Manual Entry"),
                            ("WEB_PORTAL", "Web Portal"),
                            ("API", "API"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                (
                    "workflow_type",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard Investigation"),
                            ("EXPEDITED", "Expedited"),
                            ("FULL", "Full Investigation"),
                            ("PARTIAL", "Partial Investigation"),
                        ],
                        default="STANDARD",
                        max_length=50,
                    ),
                ),
                (
                    "investigation_progress",
                    models.IntegerField(
                        default=0, help_text="Investigation progress percentage (0-100)"
                    ),
                ),
                (
                    "chk_spot",
                    models.BooleanField(
                        default=False, help_text="Spot investigation completed"
                    ),
                ),
                (
                    "chk_hospital",
                    models.BooleanField(
                        default=False, help_text="Hospital verification completed"
                    ),
                ),
                (
                    "chk_claimant",
                    models.BooleanField(
                        default=False, help_text="Claimant verification completed"
                    ),
                ),
                (
                    "chk_insured",
                    models.BooleanField(
                        default=False, help_text="Insured verification completed"
                    ),
                ),
                (
                    "chk_witness",
                    models.BooleanField(
                        default=False, help_text="Witness statement recorded"
                    ),
                ),
                (
                    "chk_driver",
                    models.BooleanField(
                        default=False, help_text="Driver verification completed"
                    ),
                ),
                (
                    "chk_dl",
                    models.BooleanField(
                        default=False, help_text="Driving License verified"
                    ),
                ),
                (
                    "chk_rc",
                    models.BooleanField(
                        default=False, help_text="RC verification completed"
                    ),
                ),
                (
                    "chk_permit",
                    models.BooleanField(
                        default=False, help_text="Permit verification completed"
                    ),
                ),
                (
                    "chk_court",
                    models.BooleanField(
                        default=False, help_text="Court records obtained"
                    ),
                ),
                (
                    "chk_notice",
                    models.BooleanField(
                        default=False, help_text="Notice verification completed"
                    ),
                ),
                (
                    "chk_134_notice",
                    models.BooleanField(
                        default=False, help_text="Section 134 notice verified"
                    ),
                ),
                ("chk_rti", models.BooleanField(default=False, help_text="RTI filed")),
                (
                    "chk_medical_verification",
                    models.BooleanField(
                        default=False, help_text="Medical records verified"
                    ),
                ),
                (
                    "chk_income",
                    models.BooleanField(
                        default=False, help_text="Income verification completed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="insurance_cases",
                        to="users.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_insurance_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_email",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_insurance_cases",
                        to="users.emailintake",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_insurance_cases",
                        to="users.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "insurance_case",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("POLICY", "Policy Document"),
                            ("PETITION", "Petition Copy"),
                            ("FIR", "FIR Copy"),
                            ("MEDICAL", "Medical Report"),
                            ("SPOT_PHOTO", "Spot Photograph"),
                            ("DL", "Driving License"),
                            ("RC", "Registration Certificate"),
                            ("PERMIT", "Permit"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("document_name", models.CharField(max_length=500)),
                ("file_path", models.FileField(upload_to="case_documents/%Y/%m/%d/")),
                ("extracted_text", models.TextField(blank=True)),
                ("extracted_data", models.JSONField(blank=True, default=dict)),
                ("uploaded_date", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email_attachment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_case_documents",
                        to="users.emailattachment",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="users.insurancecase",
                    ),
                ),
            ],
            options={
                "db_table": "case_document",
                "ordering": ["-uploaded_date"],
            },
        ),
        migrations.CreateModel(
            name="EvidencePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_id",
                    models.IntegerField(
                        db_index=True, help_text="Reference to cases_case table"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        help_text="Evidence photo with GPS metadata",
                        upload_to="evidence_photos/%Y/%m/%d/",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="GPS latitude from photo EXIF data (REQUIRED)",
                        max_digits=9,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="GPS longitude from photo EXIF data (REQUIRED)",
                        max_digits=9,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=500)),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_size",
                    models.BigIntegerField(default=0, help_text="File size in bytes"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_photos",
                        to="users.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "evidence_photo",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["case_id", "uploaded_at"],
                        name="evidence_ph_case_id_c8909b_idx",
                    ),
                    models.Index(
                        fields=["vendor", "uploaded_at"],
                        name="evidence_ph_vendor__b65e78_idx",
                    ),
                    models.Index(
                        fields=["case_id", "vendor"],
                        name="evidence_ph_case_id_ffa564_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="insurancecase",
            index=models.Index(
                fields=["case_number"], name="insurance_c_case_nu_72bc96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insurancecase",
            index=models.Index(
                fields=["claim_number"], name="insurance_c_claim_n_381889_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insurancecase",
            index=models.Index(fields=["status"], name="insurance_c_status_1926b3_idx"),
        ),
        migrations.AddIndex(
            model_name="insurancecase",
            index=models.Index(
                fields=["category"], name="insurance_c_categor_a449ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insurancecase",
            index=models.Index(
                fields=["priority"], name="insurance_c_priorit_c0b963_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insurancecase",
            index=models.Index(
                fields=["created_at"], name="insurance_c_created_a3e8a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casedocument",
            index=models.Index(
                fields=["case", "document_type"], name="case_docume_case_id_654b60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casedocument",
            index=models.Index(
                fields=["uploaded_date"], name="case_docume_uploade_fbeb66_idx"
            ),
        ),
    ]
