# Generated by Django 6.0.1 on 2026-02-19 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_add_insurance_case_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_type",
                    models.CharField(
                        choices=[
                            ("CLAIMANT_CHECK", "Claimant Verification"),
                            ("INSURED_CHECK", "Insured Verification"),
                            ("DRIVER_CHECK", "Driver Verification"),
                            ("SPOT_CHECK", "Spot Investigation"),
                            ("CHARGESHEET", "Chargesheet Verification"),
                        ],
                        db_index=True,
                        help_text="Type of verification check",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                            ("REQUIRES_REVISION", "Requires Revision"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Current status of this verification",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        help_text="Priority level for this verification",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title/summary of verification task",
                        max_length=500,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of what needs to be verified",
                    ),
                ),
                (
                    "findings",
                    models.TextField(
                        blank=True, help_text="Detailed findings from the verification"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes, observations, or comments",
                    ),
                ),
                (
                    "location_address",
                    models.TextField(
                        blank=True, help_text="Address where verification was conducted"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="GPS latitude of verification location",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="GPS longitude of verification location",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "person_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of person being verified (claimant/insured/driver)",
                        max_length=500,
                    ),
                ),
                (
                    "person_phone",
                    models.CharField(
                        blank=True, help_text="Contact phone number", max_length=20
                    ),
                ),
                (
                    "person_email",
                    models.EmailField(
                        blank=True, help_text="Contact email address", max_length=254
                    ),
                ),
                (
                    "person_address",
                    models.TextField(
                        blank=True, help_text="Address of person being verified"
                    ),
                ),
                (
                    "identification_number",
                    models.CharField(
                        blank=True,
                        help_text="ID number (Aadhar/PAN/DL/etc)",
                        max_length=100,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of document verified (DL/RC/Permit/etc)",
                        max_length=100,
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        help_text="Document registration/license number",
                        max_length=100,
                    ),
                ),
                (
                    "document_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the document was verified as authentic",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this verification was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this was assigned to an investigator",
                        null=True,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When work on this verification started",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this verification was completed",
                        null=True,
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this verification was approved/verified",
                        null=True,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="User/Investigator assigned to perform this verification",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        help_text="The insurance case this verification belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="users.insurancecase",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who completed/verified this check",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Case Verification",
                "verbose_name_plural": "Case Verifications",
                "db_table": "case_verification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(help_text="Comment text")),
                (
                    "is_internal",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is an internal comment (not visible to client)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this comment was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this comment was last updated"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this comment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verification_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verification",
                    models.ForeignKey(
                        help_text="The verification this comment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="users.caseverification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verification Comment",
                "verbose_name_plural": "Verification Comments",
                "db_table": "verification_comment",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("PHOTO", "Photograph"),
                            ("SCAN", "Scanned Document"),
                            ("PDF", "PDF Document"),
                            ("VIDEO", "Video Recording"),
                            ("AUDIO", "Audio Recording"),
                            ("REPORT", "Investigation Report"),
                            ("STATEMENT", "Written Statement"),
                            ("CERTIFICATE", "Certificate"),
                            ("OTHER", "Other"),
                        ],
                        default="PHOTO",
                        help_text="Type of document",
                        max_length=30,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Document title/description", max_length=500
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the document"
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Path to the uploaded file", max_length=1000
                    ),
                ),
                (
                    "file_name",
                    models.CharField(help_text="Original filename", max_length=500),
                ),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, help_text="MIME type of the file", max_length=100
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this document was uploaded"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this document has been verified as authentic",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the primary/main document for this verification",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this document"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who uploaded this document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_verification_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verification",
                    models.ForeignKey(
                        help_text="The verification this document belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="users.caseverification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verification Document",
                "verbose_name_plural": "Verification Documents",
                "db_table": "verification_document",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="caseverification",
            index=models.Index(
                fields=["case", "verification_type"],
                name="case_verifi_case_id_9462db_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="caseverification",
            index=models.Index(
                fields=["status", "priority"], name="case_verifi_status_227b27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caseverification",
            index=models.Index(
                fields=["assigned_to", "status"], name="case_verifi_assigne_4474b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caseverification",
            index=models.Index(
                fields=["created_at"], name="case_verifi_created_c790a7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="caseverification",
            unique_together={("case", "verification_type")},
        ),
        migrations.AddIndex(
            model_name="verificationcomment",
            index=models.Index(
                fields=["verification", "created_at"],
                name="verificatio_verific_842024_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationdocument",
            index=models.Index(
                fields=["verification", "document_type"],
                name="verificatio_verific_480013_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationdocument",
            index=models.Index(
                fields=["uploaded_at"], name="verificatio_uploade_91906e_idx"
            ),
        ),
    ]
