# Generated by Django 5.1.4 on 2026-07-20 10:44

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_vendor_push_tokens'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE claimant_checks RENAME COLUMN observation TO triggers;
                ALTER TABLE insured_checks RENAME COLUMN observation TO triggers;
                ALTER TABLE driver_checks RENAME COLUMN observation TO triggers;
                ALTER TABLE spot_checks RENAME COLUMN observations TO triggers;
                ALTER TABLE chargesheets RENAME COLUMN observations TO triggers;

                ALTER TABLE cases ADD COLUMN policy_document TEXT DEFAULT '';
                ALTER TABLE cases ADD COLUMN petition_document TEXT DEFAULT '';
            """,
            reverse_sql="""
                ALTER TABLE cases DROP COLUMN petition_document;
                ALTER TABLE cases DROP COLUMN policy_document;

                ALTER TABLE chargesheets RENAME COLUMN triggers TO observations;
                ALTER TABLE spot_checks RENAME COLUMN triggers TO observations;
                ALTER TABLE driver_checks RENAME COLUMN triggers TO observation;
                ALTER TABLE insured_checks RENAME COLUMN triggers TO observation;
                ALTER TABLE claimant_checks RENAME COLUMN triggers TO observation;
            """
        )
    ]
