# Generated by Django 6.0.1 on 2026-07-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_add_fir_date_and_reason_to_claimant'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='qc',
            new_name='users_qc_bar_reg_f06e00_idx',
            old_name='users_lawye_bar_reg_83489e_idx',
        ),
        migrations.RenameIndex(
            model_name='qc',
            new_name='users_qc_special_2a826a_idx',
            old_name='users_lawye_special_0466be_idx',
        ),
        migrations.RenameIndex(
            model_name='qc',
            new_name='users_qc_is_acti_89f4e7_idx',
            old_name='users_lawye_is_acti_dca089_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='reports_assigne_d96e98_idx',
            old_name='reports_assigne_9bcb07_idx',
        ),
    ]
