# Generated by Django 6.0.1 on 2026-07-27 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_rename_users_lawye_bar_reg_83489e_idx_users_qc_bar_reg_f06e00_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=255)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='admin',
            name='users_admin_employe_73d5ae_idx',
        ),
        migrations.RemoveIndex(
            model_name='admin',
            name='users_admin_departm_040d12_idx',
        ),
        migrations.RemoveIndex(
            model_name='admin',
            name='users_admin_is_acti_d2dd23_idx',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super CaseManager'), ('CASE_MANAGER', 'CaseManager'), ('VENDOR', 'Vendor'), ('CLIENT', 'Client'), ('QC', 'QC')], db_index=True, default='CLIENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_role',
            field=models.CharField(blank=True, choices=[('CASE_HANDLER', 'Case Handler'), ('REPORT_MANAGER', 'Report Manager'), ('LOG_MANAGER', 'Log Manager'), ('SUPER_ADMIN', 'Super CaseManager')], help_text='Sub-role for caseManager users only', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='casemanager',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'CASE_MANAGER'}, on_delete=django.db.models.deletion.CASCADE, related_name='caseManager_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
        migrations.AddIndex(
            model_name='casemanager',
            index=models.Index(fields=['employee_id'], name='users_casem_employe_575c23_idx'),
        ),
        migrations.AddIndex(
            model_name='casemanager',
            index=models.Index(fields=['department'], name='users_casem_departm_14f177_idx'),
        ),
        migrations.AddIndex(
            model_name='casemanager',
            index=models.Index(fields=['is_active'], name='users_casem_is_acti_1be742_idx'),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
