# Generated by Django 6.0.1 on 2026-07-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_casemanager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('CASE_MANAGER', 'Case Manager'), ('VENDOR', 'Vendor'), ('CLIENT', 'Client'), ('QC', 'QC')], db_index=True, default='CLIENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_role',
            field=models.CharField(blank=True, choices=[('CASE_HANDLER', 'Case Handler'), ('REPORT_MANAGER', 'Report Manager'), ('LOG_MANAGER', 'Log Manager'), ('SUPER_ADMIN', 'Super Admin')], help_text='Sub-role for case manager users only', max_length=20, null=True),
        ),
    ]
