export const theme = {
  colors: {
    primary: '#0F5FA8',
    primaryDark: '#0A4274',
    primarySoft: '#E7F1FB',
    secondary: '#F28C28',
    secondarySoft: '#FFF3E3',
    success: '#2E9B62',
    successSoft: '#E9F8F0',
    warning: '#D9822B',
    warningSoft: '#FFF5E8',
    error: '#D64545',
    errorSoft: '#FDECEC',
    info: '#3A7BD5',
    infoSoft: '#EDF4FF',
    background: '#F4F7FB',
    surface: '#FFFFFF',
    surfaceMuted: '#F8FAFC',
    text: '#132238',
    textSecondary: '#5F7187',
    textMuted: '#8A97A8',
    border: '#D8E1EC',
    divider: '#E7EDF4',
    overlay: 'rgba(12, 31, 53, 0.08)',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  borderRadius: {
    sm: 4,
    md: 8,
    lg: 12,
    xl: 20,
    full: 999,
  },
  shadows: {
    card: {
      shadowColor: '#0C1F35',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.08,
      shadowRadius: 18,
      elevation: 4,
    },
    floating: {
      shadowColor: '#0C1F35',
      shadowOffset: { width: 0, height: 14 },
      shadowOpacity: 0.14,
      shadowRadius: 24,
      elevation: 8,
    },
  },
};

export type Theme = typeof theme;
